// Mocks generated by Mockito 5.3.2 from annotations
// in login/test/user_repository_mock.mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:login/domain/entity/user.dart' as _i3;
import 'package:login/helper/user_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void addUser(_i3.User? user) => super.noSuchMethod(
        Invocation.method(
          #addUser,
          [user],
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<_i3.User> getUsers() => (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
        ),
        returnValue: <_i3.User>[],
      ) as List<_i3.User>);
  @override
  _i3.User? logar(
    String? login,
    String? senha,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #logar,
        [
          login,
          senha,
        ],
      )) as _i3.User?);
  @override
  _i3.User? getUserById(String? login) => (super.noSuchMethod(Invocation.method(
        #getUserById,
        [login],
      )) as _i3.User?);
}
